name: {{cookiecutter.project_name}}}
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - altair
  - eli5
  - pandas
  - pandas-profiling
  - holoviews
  - hvplot
  - pip:
    - ase
    - edward
    - dvc
    - matminer
    - csvkit

